# @package _global_
# Data
data_dir: "data"
ckpt_dir: "ckpt"
name: "baseline"

# Model
model: "resnet50"
seed: 

# Training
batch_size: 16
epoch_per: 99
lr: 0.0001
task_binary: True
early_stop: 10

# Incremental
num_exp: 5
rounds: 4
samples_start: 10000
samples_test: 10000
train_dist: [0.8, 0.8, 0.8, 0.8, 0.8]
test_dist: [0.5, 0.5, 0.5, 0.5, 0.5]