# @package confs.test
# Data
data_dir: "data"
ckpt_dir: "ckpt"
name: "nini"

# Model
model: "jojo"
seed: random.randint(0, 9999999)

# Training
batch_size: 16
epoch_per: 99
lr: 0.0001
task_binary: True
early_stop: 10

# Incremental
num_exp: 5
rounds: 4
samples_start: 10000
samples_test: 10000
